// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkflowEngine.Infrastructure.Data;

#nullable disable

namespace WorkflowEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216062055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowEngine.Core.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentProcessId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentProcessId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultConditionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCommentRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProcessStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeoutActionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultConditionId")
                        .IsUnique();

                    b.HasIndex("ProcessStepId");

                    b.HasIndex("TargetStepId");

                    b.HasIndex("TimeoutActionId");

                    b.ToTable("ProcessActions");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessActionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessActionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleExpression")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("TargetStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessActionId");

                    b.HasIndex("TargetStepId");

                    b.ToTable("ProcessActionConditions");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("ProcessSteps");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.Process", b =>
                {
                    b.HasOne("WorkflowEngine.Core.Entities.Process", "ParentProcess")
                        .WithMany()
                        .HasForeignKey("ParentProcessId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProcess");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessAction", b =>
                {
                    b.HasOne("WorkflowEngine.Core.Entities.ProcessActionCondition", "DefaultCondition")
                        .WithOne()
                        .HasForeignKey("WorkflowEngine.Core.Entities.ProcessAction", "DefaultConditionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkflowEngine.Core.Entities.ProcessStep", "ProcessStep")
                        .WithMany("Actions")
                        .HasForeignKey("ProcessStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Core.Entities.ProcessStep", "TargetStep")
                        .WithMany()
                        .HasForeignKey("TargetStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkflowEngine.Core.Entities.ProcessAction", "TimeoutAction")
                        .WithMany()
                        .HasForeignKey("TimeoutActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultCondition");

                    b.Navigation("ProcessStep");

                    b.Navigation("TargetStep");

                    b.Navigation("TimeoutAction");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessActionCondition", b =>
                {
                    b.HasOne("WorkflowEngine.Core.Entities.ProcessAction", "ProcessAction")
                        .WithMany("Conditions")
                        .HasForeignKey("ProcessActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Core.Entities.ProcessStep", "TargetStep")
                        .WithMany()
                        .HasForeignKey("TargetStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcessAction");

                    b.Navigation("TargetStep");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessStep", b =>
                {
                    b.HasOne("WorkflowEngine.Core.Entities.Process", "Process")
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.Process", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessAction", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("WorkflowEngine.Core.Entities.ProcessStep", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
